# Generated by Django 2.1.3 on 2018-11-24 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_of_order', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('total_discount', models.IntegerField()),
                ('ordered_at', models.DateTimeField(verbose_name='date ordered')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('number', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('number', models.IntegerField()),
                ('created_at', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('image_url', models.CharField(max_length=1000)),
                ('dough_layer', models.CharField(choices=[('L', 'Thin'), ('A', 'Average'), ('B', 'Plump')], max_length=1)),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('created_at', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant_Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('number', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='manager',
            name='restaurant_branch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Restaurant_Branch'),
        ),
        migrations.AddField(
            model_name='cart',
            name='manager_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Manager'),
        ),
    ]
