# Generated by Django 2.1.3 on 2018-11-24 06:59

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount_of_Order', models.IntegerField()),
                ('Total_Price', models.IntegerField()),
                ('Total_Discount', models.IntegerField()),
                ('Ordered_At', models.DateTimeField(default=datetime.datetime(2018, 11, 24, 6, 59, 26, 820039, tzinfo=utc), verbose_name='date ordered')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Surname', models.CharField(max_length=200)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('Number', models.IntegerField()),
                ('Address', models.CharField(max_length=200)),
                ('Created_At', models.DateTimeField(default=datetime.datetime(2018, 11, 24, 6, 59, 26, 819055, tzinfo=utc), verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Surname', models.CharField(max_length=200)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('Number', models.IntegerField()),
                ('Created_At', models.DateTimeField(default=datetime.datetime(2018, 11, 24, 6, 59, 26, 819555, tzinfo=utc), verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Filling', models.CharField(max_length=500)),
                ('Dough_Layer', models.CharField(choices=[('L', 'Thin'), ('A', 'Average'), ('B', 'Plump')], default='A', max_length=1)),
                ('Price', models.IntegerField()),
                ('Discount', models.IntegerField()),
                ('Created_At', models.DateTimeField(default=datetime.datetime(2018, 11, 24, 6, 59, 26, 820559, tzinfo=utc), verbose_name='date created')),
                ('Cart_ID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.Cart')),
            ],
        ),
        migrations.CreateModel(
            name='Pizza_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created_At', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant_Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Number', models.IntegerField()),
                ('Address', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='pizza',
            name='List_ID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.Pizza_List'),
        ),
        migrations.AddField(
            model_name='manager',
            name='Restaurant_Branch_ID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.Restaurant_Branch'),
        ),
        migrations.AddField(
            model_name='cart',
            name='Manager_ID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.Manager'),
        ),
    ]
