# Generated by Django 2.1.3 on 2018-11-24 07:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Ordered_At',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 24, 7, 34, 55, 660859, tzinfo=utc), verbose_name='date ordered'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Created_At',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 24, 7, 34, 55, 659856, tzinfo=utc), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='Created_At',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 24, 7, 34, 55, 660358, tzinfo=utc), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='Created_At',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 24, 7, 34, 55, 661862, tzinfo=utc), verbose_name='date created'),
        ),
    ]
