# Generated by Django 2.1.3 on 2018-11-24 09:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Ordered_At',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 24, 9, 24, 5, 652067, tzinfo=utc), verbose_name='date ordered'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Created_At',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 24, 9, 24, 5, 651061, tzinfo=utc), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='Created_At',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 24, 9, 24, 5, 652067, tzinfo=utc), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='Created_At',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 24, 9, 24, 5, 653072, tzinfo=utc), verbose_name='date created'),
        ),
    ]
