# Generated by Django 2.1.3 on 2018-11-18 20:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount_of_Order', models.IntegerField()),
                ('Total_Price', models.IntegerField()),
                ('Total_Discount', models.FloatField()),
                ('Ordered_At', models.DateTimeField(default=datetime.datetime(2018, 11, 18, 20, 1, 8, 204548, tzinfo=utc), verbose_name='date ordered')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Surname', models.CharField(max_length=200)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('Number', models.IntegerField()),
                ('Created_At', models.DateTimeField(default=datetime.datetime(2018, 11, 18, 20, 1, 8, 204047, tzinfo=utc), verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant_Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Number', models.IntegerField()),
                ('Address', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='Created_At',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 18, 20, 1, 8, 202542, tzinfo=utc), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='Dough_Layer',
            field=models.CharField(choices=[('L', 'Thin'), ('A', 'Average'), ('B', 'Plump')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='manager',
            name='Restaurant_Branch_ID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.Restaurant_Branch'),
        ),
        migrations.AddField(
            model_name='cart',
            name='Manager_ID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.Manager'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='Cart_ID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.Cart'),
        ),
    ]
