# Generated by Django 2.1.3 on 2018-11-23 11:08

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created_At', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.AlterField(
            model_name='cart',
            name='Ordered_At',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 23, 11, 8, 57, 303566, tzinfo=utc), verbose_name='date ordered'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Created_At',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 23, 11, 8, 57, 302564, tzinfo=utc), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='Created_At',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 23, 11, 8, 57, 303566, tzinfo=utc), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='Created_At',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 23, 11, 8, 57, 304569, tzinfo=utc), verbose_name='date created'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='List_ID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.Pizza_List'),
        ),
    ]
