# Generated by Django 2.1.3 on 2018-11-18 20:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181119_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Ordered_At',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 18, 20, 9, 26, 324704, tzinfo=utc), verbose_name='date ordered'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='Total_Discount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Created_At',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 18, 20, 9, 26, 322698, tzinfo=utc), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='Created_At',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 18, 20, 9, 26, 323701, tzinfo=utc), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='Discount',
            field=models.IntegerField(),
        ),
    ]
