# Generated by Django 2.1.3 on 2018-11-23 12:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181123_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Ordered_At',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 23, 12, 16, 39, 682, tzinfo=utc), verbose_name='date ordered'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Created_At',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 23, 12, 16, 38, 999679, tzinfo=utc), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='Created_At',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 23, 12, 16, 39, 682, tzinfo=utc), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='Created_At',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 23, 12, 16, 39, 1183, tzinfo=utc), verbose_name='date created'),
        ),
    ]
